name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package and dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ./src[dev]

      - name: Lint (ruff)
        run: ruff check src/nautobot_mcp_server tests

      - name: Format check (black)
        run: black --check src/nautobot_mcp_server tests

      - name: Import order (isort)
        run: isort --check-only src/nautobot_mcp_server tests

      - name: Type check (mypy)
        run: mypy src/nautobot_mcp_server

      - name: Tests
        run: pytest -q --maxfail=1 --disable-warnings --cov=nautobot_mcp_server --cov-report=term-missing --cov-fail-under=70

      - name: Build Docker
        run: docker build -t nautobot-mcp:ci -f src/Dockerfile .

