name: Manual Release Prep

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (e.g., v0.1.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -e ./src[dev]
          pytest -q
      - name: Build Docker (no push)
        run: docker build -t nautobot-mcp:${{ github.event.inputs.version }} -f src/Dockerfile .
      - name: Summary
        run: echo "Built and tested ${{ github.event.inputs.version }}. Tag and publish manually when ready."

